export const APP_ERROR_CODES = {
  AUTH_GOOGLE_EMAIL_MISSING: 'AUTH_GOOGLE_EMAIL_MISSING',
  AUTH_SESSION_INIT_FAILED: 'AUTH_SESSION_INIT_FAILED',
  AUTH_REFRESH_TOKEN_INVALID_TYPE: 'AUTH_REFRESH_TOKEN_INVALID_TYPE',
  AUTH_REFRESH_USER_NOT_FOUND: 'AUTH_REFRESH_USER_NOT_FOUND',
  AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_INVALID_OR_EXPIRED:
    'AUTH_REFRESH_TOKEN_INVALID_OR_EXPIRED',
} as const;

export type AppErrorCode =
  (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
