version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: fatelink-be-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-dev-data:/data

volumes:
  redis-dev-data:
