export const AUTH_ENV = {
  jwtSecret: 'JWT_SECRET',
  refreshJwtSecret: 'REFRESH_JWT_SECRET',
  jwtAccessExpiresIn: 'JWT_ACCESS_EXPIRES_IN',
  jwtRefreshExpiresIn: 'JWT_REFRESH_EXPIRES_IN',
  googleClientId: 'GOOGLE_CLIENT_ID',
  facebookGraphApiUrl: 'FACEBOOK_GRAPH_API_URL',
  zaloGraphApiUrl: 'ZALO_GRAPH_API_URL',
  tiktokApiUrl: 'TIKTOK_API_URL',
  tiktokClientKey: 'TIKTOK_CLIENT_KEY',
  tiktokClientSecret: 'TIKTOK_CLIENT_SECRET',
  tiktokRedirectUri: 'TIKTOK_REDIRECT_URI',
  authExposeDebugChallenges: 'AUTH_EXPOSE_DEBUG_CHALLENGES',
  emailFromAddress: 'EMAIL_FROM_ADDRESS',
  gmailSmtpUser: 'GMAIL_SMTP_USER',
  gmailSmtpAppPassword: 'GMAIL_SMTP_APP_PASSWORD',
  gmailSmtpHost: 'GMAIL_SMTP_HOST',
  gmailSmtpPort: 'GMAIL_SMTP_PORT',
  phoneOtpExpiresInMinutes: 'PHONE_OTP_EXPIRES_IN_MINUTES',
  twilioAccountSid: 'TWILIO_ACCOUNT_SID',
  twilioAuthToken: 'TWILIO_AUTH_TOKEN',
  twilioFromNumber: 'TWILIO_FROM_NUMBER',
  twilioMessagingServiceSid: 'TWILIO_MESSAGING_SERVICE_SID',
  twilioEndpoint: 'TWILIO_ENDPOINT',
  twilioOtpTemplate: 'TWILIO_OTP_TEMPLATE',
  magicLinkExpiresInMinutes: 'MAGIC_LINK_EXPIRES_IN_MINUTES',
  magicLinkBaseUrl: 'MAGIC_LINK_BASE_URL',
} as const;
