export const ERROR_CATEGORY = {
  BAD_REQUEST: 'BAD_REQUEST',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCategory =
  (typeof ERROR_CATEGORY)[keyof typeof ERROR_CATEGORY];

export const ERROR_CODES = {
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',

  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_ACCESS_TOKEN: 'AUTH_INVALID_ACCESS_TOKEN',
  AUTH_ADMIN_TOKEN_FORBIDDEN: 'AUTH_ADMIN_TOKEN_FORBIDDEN',
  AUTH_SESSION_ISSUE_FAILED: 'AUTH_SESSION_ISSUE_FAILED',
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_REVOKE_FORBIDDEN: 'AUTH_SESSION_REVOKE_FORBIDDEN',
  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_EMAIL_REGISTRATION_REQUIRES_VERIFICATION:
    'AUTH_EMAIL_REGISTRATION_REQUIRES_VERIFICATION',
  AUTH_INVALID_EMAIL_CREDENTIALS: 'AUTH_INVALID_EMAIL_CREDENTIALS',
  AUTH_EMAIL_ACCOUNT_NOT_FOUND: 'AUTH_EMAIL_ACCOUNT_NOT_FOUND',
  AUTH_GOOGLE_TOKEN_REQUIRED: 'AUTH_GOOGLE_TOKEN_REQUIRED',
  AUTH_GOOGLE_TOKEN_INVALID: 'AUTH_GOOGLE_TOKEN_INVALID',
  AUTH_GOOGLE_PROFILE_ORPHANED: 'AUTH_GOOGLE_PROFILE_ORPHANED',
  AUTH_FACEBOOK_TOKEN_REQUIRED: 'AUTH_FACEBOOK_TOKEN_REQUIRED',
  AUTH_FACEBOOK_TOKEN_INVALID: 'AUTH_FACEBOOK_TOKEN_INVALID',
  AUTH_FACEBOOK_EMAIL_MISSING: 'AUTH_FACEBOOK_EMAIL_MISSING',
  AUTH_FACEBOOK_PROFILE_ORPHANED: 'AUTH_FACEBOOK_PROFILE_ORPHANED',
  AUTH_MAGIC_LINK_INVALID: 'AUTH_MAGIC_LINK_INVALID',
  AUTH_MAGIC_LINK_MALFORMED: 'AUTH_MAGIC_LINK_MALFORMED',
  AUTH_PHONE_OTP_INVALID: 'AUTH_PHONE_OTP_INVALID',
  AUTH_PHONE_OTP_ATTEMPTS_EXCEEDED: 'AUTH_PHONE_OTP_ATTEMPTS_EXCEEDED',
  AUTH_PHONE_ACCOUNT_NOT_FOUND: 'AUTH_PHONE_ACCOUNT_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
